### ISSUE TITLE
Some feedbacks after I finished my codelabs

### ISSUE THREAD

**Issue by toanvc** [googlecodelabs/exoplayer-intro#1]
* wrong link from git

> git clone https://github.com/googlecodelabs/exoplayer-intro.git

Should be: 

> git clone https://github.com/googlecodelabs/exoplayer-codelab-io17.git

* In Step 7, `google_2015_logo` should be `google_2017_logo`
* in Step 2, I see exoplayer-codelab-0x (x = 0..4) but in the labs, there are only 3 of them are used (exoplayer-codelab-00, 01, 02). It made me confused.

**Comment by marcbaechinger** [comment]
Thanks. I consider this when updating.
