### ISSUE TITLE
ExtractorMediaSource deprecated (using with 2.6.1 release)

### ISSUE THREAD

**Issue by pavangayakwad** [googlecodelabs/exoplayer-intro#10]
The Android Studio warns me that ExtractorMediaSource is deprecated. Request to update the tutorial accordingly. Thanks.

![image](https://user-images.githubusercontent.com/1834890/34551114-9a880e12-f13c-11e7-86cc-e4d0d284d60b.png)

**Comment by marcbaechinger** [comment]
Thanks for reporting!

I'm currently updating the codelab. The updated version will use the factory with 2.6.1. It's fixed and will be available as soon as I push the new version.
