### ISSUE TITLE
update text about AdaptiveVideoTrackSelection as class doesnt exist anymore

### ISSUE THREAD

**Issue by dpreussler** [googlecodelabs/exoplayer-intro#11]
in 
https://codelabs.developers.google.com/codelabs/exoplayer-intro/#4
this part:
_We are now streaming DASH while addressing bandwidth when selecting tracks. Create a breakpoint in the method AdaptiveVideoTrackSelection.updateSelectedTrack and start your app in debug mode. The breakpoint is hit each time a download of the next chunk is initiated and the track selector needs to make a decision for an appropriate video format._

is outdated. the class was renamed to AdaptiveTrackSelection in 2.4

**Comment by dturner** [comment]
Text has now been updated. And it only took 2 years! 😉 Thanks for filing this issue.
