### ISSUE TITLE
no logging TAG defined in PlayerActivity

### ISSUE THREAD

**Issue by dpreussler** [googlecodelabs/exoplayer-intro#12]
step 5:
https://codelabs.developers.google.com/codelabs/exoplayer-intro/#5

wants to copy in a block containing:

   Log.d(TAG, "changed state to " + stateString 
       + " playWhenReady: " + playWhenReady);

but the TAG is not defined. It would be nice to have this in or just use "" here to keep the reader focused on important things.

**Comment by dturner** [comment]
Instructions have been updated. Thanks for filing this issue.
