### ISSUE TITLE
example uses deprecated constants

### ISSUE THREAD

**Issue by dpreussler** [googlecodelabs/exoplayer-intro#13]
in
https://codelabs.developers.google.com/codelabs/exoplayer-intro/#5

the ComponentListener uses ExoPlayer constants i.e. ExoPlayer.STATE_READY
But these are deprecated and should be replaced by Player constants i.e. Player.STATE_READY

**Comment by dturner** [comment]
The constants are inherited by `ExoPlayer` from `Player` but not deprecated as far as I can see: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html

Unless there's a compelling reason to update this I suggest we leave as is.
