### ISSUE TITLE
screenshots should show the correct quick fix

### ISSUE THREAD

**Issue by dpreussler** [googlecodelabs/exoplayer-intro#14]
in 
https://codelabs.developers.google.com/codelabs/exoplayer-intro/#5

the sceenshots in section:
Using VideoRendererEventListener and AudioRendererEventListener
are showing the cast option selected. 
it would be nice to select the right one:
<img width="912" alt="screen shot 2018-01-09 at 12 54 27" src="https://user-images.githubusercontent.com/2426606/34719814-7b7d9eac-f53c-11e7-8d37-c94c766723d2.png">

People new to the hotfix option in AS might chose the wrong one

**Comment by dturner** [comment]
This section has now been removed. 

> [Q] Any hotkey for that? Loosing time waiting for the Balloon to appear…

ALT+Enter can be used to display quick fix in Android Studio
