### ISSUE TITLE
You should mention layout file name when changing SimpleExoPlayerView

### ISSUE THREAD

**Issue by dpreussler** [googlecodelabs/exoplayer-intro#15]
step
https://codelabs.developers.google.com/codelabs/exoplayer-intro/#6

starts with:
_The first simple customization is whether to not use the controller at all. This can be done easily by using the use_controller attribute on the SimpleExoPlayerView element. Set it to false and the control does not show up anymore:_

would be good to remind the reader that this is in _activity_player.xml_
Further down other examples mention that. So maybe move that hint up or always have them.

**Comment by dturner** [comment]
Filename has been added to text
