### ISSUE TITLE
No artwork while playing mp3

### ISSUE THREAD

**Issue by XtheWiz** [googlecodelabs/exoplayer-intro#17]
Hi, thank you for great codelab and I enjoy to follow instructions.
But when I nearly finished step-3, that playing mp3 file. The instruction said there should have an artwork of that file, but my screen is black with the media control at bottom. I have no idea how to get artwork to show?

**Comment by blausand** [comment]
`<confirm>`same over here. 
Testing on an Lineage 14.1 based on 7.1 (Nougat), API level 25)`</confirm>`

**Comment by dturner** [comment]
Thanks for reporting this. It should be fixed now (only took 1.5 years - sorry!)
