### ISSUE TITLE
<SEPV results into SimpleExoPlayerView and shows it as deprecated 

### ISSUE THREAD

**Issue by RamIndani** [googlecodelabs/exoplayer-intro#18]
![screen shot 2018-05-10 at 14 30 28](https://user-images.githubusercontent.com/3529605/39895403-f08c9ffa-545e-11e8-846c-7282387ae274.png)
It is mentioned in the third step of the code lab. 
![screen shot 2018-05-10 at 14 31 57](https://user-images.githubusercontent.com/3529605/39895410-fb9ca336-545e-11e8-9d65-ccc369e302af.png)

**Comment by dturner** [comment]
Fixed.
