### ISSUE TITLE
resetPosition set as true, which shouldbe false

### ISSUE THREAD

**Issue by joardar-aditya** [googlecodelabs/exoplayer-intro#19]
private void initializePlayer() {
     [...]
     Uri uri = Uri.parse(getString(R.string.media_url_mp3));
     MediaSource mediaSource = buildMediaSource(uri);
     player.prepare(mediaSource, true, false);
}
in player.prepare the reset position field( which is second should be false to enable playing from the position we left off).

**Comment by blausand** [comment]
`<confirm>`Indeed!`</confirm>`
Thanks 8}

**Comment by dturner** [comment]
Fixed. Thanks for filing.
