### ISSUE TITLE
Link broken in intro tutorial

### ISSUE THREAD

**Issue by amar-yadav** [googlecodelabs/exoplayer-intro#2]
the link corresponding to  '**almost all non-adaptive audio and video formats**' in  https://codelabs.developers.google.com/codelabs/exoplayer-intro/#2 under the section '**Ladies and gentleman! Start your engine!**' gives a 404 error.

**Comment by marcbaechinger** [comment]
Thanks for your report and sorry for the late response.  :(

This is fixed in the template and will be correct once updated.
