### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

### ISSUE THREAD

**Issue by peacemind** [googlecodelabs/exoplayer-intro#24]
I get the Code from Github

git clone https://github.com/googlecodelabs/exoplayer-intro.git

load the project and build -> got this error message.

"No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android"

Any idea how I can fix this?

**Comment by Gamurar** [comment]
I have the same problem

**Comment by dturner** [comment]
MIPS has been removed from the NDK. You should no longer get this message. Please open a new issue if you are.
