### ISSUE TITLE
[exoplayer-codelab-00] seekTo in initializePlayer() does not work

### ISSUE THREAD

**Issue by tatsuyafujisaki** [googlecodelabs/exoplayer-intro#26]
#### Problem

`seekTo(...)` in `initializePlayer()` does not work because the second parameter of the [prepare](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#prepare-com.google.android.exoplayer2.source.MediaSource-boolean-boolean-) method is set to true.

```java
private void initializePlayer() {
    // ...
    player.prepare(mediaSource, true, false);
}
```

#### Solution

Setting the second parameter of the `prepare` method to`false` makes `seekTo(...)` work.

```java
private void initializePlayer() {
    // ...
    player.prepare(mediaSource, false, false);
}
```

**Comment by dturner** [comment]
Fixed.
