### ISSUE TITLE
ExoPlayerFactory.newSimpleInstance needs Context

### ISSUE THREAD

**Issue by malwinder-s** [googlecodelabs/exoplayer-intro#29]
There is mistake in [tutorial](https://codelabs.developers.google.com/codelabs/exoplayer-intro/#2) that `Context` is not passed to `ExoPlayerFactory.newSimpleInstance()` as first parameter.

```
 player = ExoPlayerFactory.newSimpleInstance(
         new DefaultRenderersFactory(this),
         new DefaultTrackSelector(), new DefaultLoadControl());
        [...]
```
In Version 2.9.6, it is required.

**Comment by dturner** [comment]
Fixed
