### ISSUE TITLE
Typo in `3. Stream!` page

### ISSUE THREAD

**Issue by andreiverdes** [googlecodelabs/exoplayer-intro#30]
Should be `Add the PlayerView` instead of `Add the`  `P` `layerView`
On the other hand, the current version is funnier

**Comment by dturner** [comment]
> On the other hand, the current version is funnier

😄 As tempted I was to leave it as it was, I have now updated it to `PlayerView`. Thanks for filing this issue.

**Comment by andreiverdes** [comment]
Always happy to open really really relevant Issues on Github 😄
