### ISSUE TITLE
Exception Cleartext HTTP traffic not permitted

### ISSUE THREAD

**Issue by doilio** [googlecodelabs/exoplayer-intro#32]
This is How I fixed this issue.
Adding Internet permission and, the usesCleartextTraffic tag

`<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>`

**Comment by dturner** [comment]
Fixed. Code now uses HTTPS.
