### ISSUE TITLE
Typo when applying custom layout to the controller

### ISSUE THREAD

**Issue by PedroCarrillo** [googlecodelabs/exoplayer-intro#4]
We are asked to create a layout named `custom_playback_control` but then when the xml it's showed you read ` app:controller_layout_id="@layout/custom_playback_control_view"/>`. This is in step 7.

**Comment by marcbaechinger** [comment]
Thanks for reporting and sorry for the laaaaate response!

This is fixed in the codelab template and will be pushed to production soon. Many thanks!
