### ISSUE TITLE
If you start codelab from any step besides step 4, you're missing the icon and string needed in final step

### ISSUE THREAD

**Issue by ceruleanotter** [googlecodelabs/exoplayer-intro#42]
Final step claims:

"You can continue updating your current project or return to a known working state by importing the project from exoplayer-intro/exoplayer-codelab-04."

But you need two files that are not included in previous steps:

* @string/logo
* @drawable/google_logo

Suggest just putting these in all steps!

**Comment by dturner** [comment]
Many thanks for reporting this. It should now have been fixed.
