### ISSUE TITLE
com.example.exoplayer process not listed in logcat when running in emulator

### ISSUE THREAD

**Issue by tberghuis** [googlecodelabs/exoplayer-intro#46]
Can't find a process in logcat window for running app com.example.exoplayer. Running project directly did not bother with import project. Is there a simple fix?

**Comment by dturner** [comment]
I've seen this a few times with Android Studio. Try restarting AS and trying again. It's definitely not a problem with the codelab. 

![image](https://user-images.githubusercontent.com/873212/71902191-6c79e680-3159-11ea-9927-dd8c77c3e417.png)
