### ISSUE TITLE
error: cannot find symbol class PlayerView

### ISSUE THREAD

**Issue by SamanSepahvand** [googlecodelabs/exoplayer-intro#47]
hi.first thank you for this library and then after few month work with this library  i have this error "
error: cannot find symbol class PlayerView
"
Thank you for answering the 
question.

**Comment by dturner** [comment]
It sounds like you might have forgotten to import the `PlayerView` class in `PlayerActivity`. You can do this by adding the following code in the imports section: 

```
import com.google.android.exoplayer2.ui.PlayerView;
```
