### ISSUE TITLE
Links broken on Media streaming with ExoPlayer - Adaptive streaming

### ISSUE THREAD

**Issue by anthonymonori** [googlecodelabs/exoplayer-intro#5]
In the section about **Other adaptive media formats**, 2 out of 3 links are broken and lead to a 404 screen on GitHub:

- https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaSource.java
- https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/source/smoothstreaming/SsMediaSource.java

Instead they should be:
- https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaSource.java
- https://github.com/google/ExoPlayer/blob/release-v2/library/smoothstreaming/src/main/java/com/google/android/exoplayer2/source/smoothstreaming/SsMediaSource.java

**Comment by marcbaechinger** [comment]
Thanks for reporting!

I corrected the links in the codelab template. It will be available as soon as it is pushed to production.
