### ISSUE TITLE
Link to original control laout of player is invalid [ERROR 404]

### ISSUE THREAD

**Issue by MahmoudMabrok** [googlecodelabs/exoplayer-intro#52]
here 
[codelab/#6](https://codelabs.developers.google.com/codelabs/exoplayer-intro/#6)
link [raw](https://raw.githubusercontent.com/google/ExoPlayer/release-v2/library/ui/src/main/res/layout/exo_playback_control_view.xml) is broken

**Comment by bgraknd** [comment]
The link is broken again and I could not reach the correct link.

**Comment by MahmoudMabrok** [comment]
@bgraknd 
if u have library dependency u can reach code 
u can reach it using navigate to that class/file

**Comment by bgraknd** [comment]
Thx. The link has been fixed.
