### ISSUE TITLE
"Stream!" section of Codelab uses incorrect variable in final code block

### ISSUE THREAD

**Issue by marceltex** [googlecodelabs/exoplayer-intro#53]
In the last code block in the `Stream!` section of the Codelab ([https://codelabs.developers.google.com/codelabs/exoplayer-intro/#2](https://codelabs.developers.google.com/codelabs/exoplayer-intro/#2)), an incorrect variable (`R.string.media_url_mp3`) is used.

Before the final code block the reader is instructed to change the URI in `initializePlayer` to `R.string.media_url_mp4`, but then the following line is in the code block:

```java
MediaItem mediaItem = MediaItem.fromUri(getString(R.string.media_url_mp3));
```

Shouldn't the final code block rather include the line below?

```java
MediaItem mediaItem = MediaItem.fromUri(getString(R.string.media_url_mp4));
```

**Comment by dturner** [comment]
Thanks for filing this, and apologies for the delay in updating. This will be fixed in the next hour or so.
