### ISSUE TITLE
Broken link for exoplayer control view layout

### ISSUE THREAD

**Issue by albertmiro** [googlecodelabs/exoplayer-intro#54]
The correct link to use right now is: https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/res/layout/exo_player_control_view.xml

**Comment by ezhd** [comment]
previous link was [](https://raw.githubusercontent.com/google/ExoPlayer/release-v2/library/ui/src/main/res/layout/exo_playback_control_view.xml)
so the now one should be  
[](https://raw.githubusercontent.com/google/ExoPlayer/release-v2/library/ui/src/main/res/layout/exo_player_control_view.xml
)
to be consistent

**Comment by dturner** [comment]
This should be fixed now.
