### ISSUE TITLE
DecoderInitializationException occurs while implementing Drm media source

### ISSUE THREAD

**Issue by himanshumohta-kiwitech** [googlecodelabs/exoplayer-intro#56]
We face issues with the DRM encrypted MPD URLs on Android TV devices(however, its working fine on Android mobile devices and Android TV emulators) while the non-encrypted URLs are working fine. 

We are getting the "MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome.secure.Format"

We are initiating two instances of the player at the same time, one is for live streaming and the other for video-on-demand content. We are facing the issue only for video-on-demand content. But if we use only one player at a time it's working fine on real Android TV devices.

Here is the video-on-demand link we have used/tested:
https://e3ed58e1e3c374eda698a424a11aebee.egress.mediapackage-vod.us-east-1.amazonaws.com/out/v1/494048d66a244aa9892379629448d166/138b3fc7a3684793a728b23f431acfca/819e73eabaee4ce69400f6775496acad/index.mpd)

**Comment by dturner** [comment]
This isn't an issue with the codelab. If you have issues with ExoPlayer please file them at: https://github.com/google/ExoPlayer/issues
