### ISSUE TITLE
Override the default style: Use "exo_player_control_view" instead of "exo_playback_control_view"

### ISSUE THREAD

**Issue by LCortezPT** [googlecodelabs/exoplayer-intro#59]
In the last step there a mention:

Another approach is to override the default layout file which PlayerControlView uses. The source code of PlayerControlView tells us that it uses **R.layout.exo_playback_control_view** for layout. If you create our own layout file with the same filename, the PlayerControlView uses your file instead.

It should be: **R.layout.exo_player_control_view**

The same goes for the name of the layout XML file: use **exo_player_control_view.xml** instead of **exo_playback_control_view.xml**

**Comment by dturner** [comment]
Many thanks for spotting and filing this issue. The codelab has been updated: https://developer.android.com/codelabs/exoplayer-intro#6

**Comment by LCortezPT** [comment]
Welcome @dturner, excelent codelab! 👍
