### ISSUE TITLE
Use of deprecated API on Media streaming with Exoplayer - Measure Quality of Experience

### ISSUE THREAD

**Issue by anthonymonori** [googlecodelabs/exoplayer-intro#6]
Under section **_Register an event listener_**, the following code-block is shown:

```java
private void initializePlayer() {
 if (player == null) {
   [...]
   player = ExoPlayerFactory.newSimpleInstance(this,
       new DefaultTrackSelector(adaptiveVideoTrackSelectionFactory),
       new DefaultLoadControl());
   
   player.addListener(componentListener); 
   [...]
}
```

It uses `ExoPlayerFactory#newSimpleInstance(Context, TrackSelector, LoadControl)` over `ExoPlayerFactory#newSimpleInstance(RenderersFactory, TrackSelector, LoadControl)`

The project contains the correct code, but the online tutorial does not.

**Comment by marcbaechinger** [comment]
Thanks for reporting!

I'm updating to 2.6.1 with the tutorial. Will be pushed to production soon. Thanks!
