### ISSUE TITLE
Exoplayer Android SDK- Transferring media in .exo format to a peer phone application and allow the peer to play the content. 

### ISSUE THREAD

**Issue by pratimagauns** [googlecodelabs/exoplayer-intro#72]
My use case is:
1. Bob with my app installed, would download a DASH Widevine DRM MP4 video from cloud using Android Exoplayer SDK.
2. We allow Bob to transfer the content to another user(Nick) using my app via WiFiDirect.
3. After transfer complete, Nick can received the Widevine license from cloud for the content and begin play from local cache. 

For this, the approach I wish to follow is to transfer the chuck of .exo files associated with the content Bob wishes to transfer Nick. I investigated a bit on this and noticed that just transferring the .exo files does not make any sense to Nick to play it from cache. After downloading content, Exoplayer also maintains a mapping of .exo files with below tables in the Sqlite DB:
``ExoplayerDownloads``
``ExoplayerCacheIndex``
``ExoplayerCacheMetadata``

Queries:
1. Along with the .exo files, can I send the mapping by extracting the records from the DB tables into a json format and then insert them at Nick's end.
2. What are the relevant fields that the player uses from the above DB tables to play the media from cache. The table contains some blob fields which didn't make much sense to me. Would be good if i get a basic understanding of the structure.

Awaiting response.

**Comment by dturner** [comment]
This question isn't specific to the codelab. Please post on the [ExoPlayer github site](https://github.com/google/ExoPlayer) instead.
