### ISSUE TITLE
Render problem due to missing id when copy-pasting exo_player_control_view

### ISSUE THREAD

**Issue by anthonymonori** [googlecodelabs/exoplayer-intro#8]
According to **Customizing the appearance of PlaybackControlView**, we are instructed to copy the contents of the `exo_player_control_view` from [here](https://raw.githubusercontent.com/google/ExoPlayer/release-v2/library/ui/src/main/res/layout/exo_playback_control_view.xml) into our new layout inside the codelab project, but the following ID cannot be found:

> @id/exo_repeat_toggle

Any idea why? Different version of ExoPlayer used that does not come with that resource ID? Was it changed?

**Comment by marcbaechinger** [comment]
Thanks for reporting and sorry for my very late reply.

Yes, seems like the layout file changed. I'm updating the codelab to the newest version right now and will push soon. So this should be fixed with this.
