### ISSUE TITLE
Error: Could not initialize class org.jetbrains.kotlin.kapt.idea.KaptModelBuilderService

### ISSUE THREAD

**Issue by KChernenko** [googlecodelabs/exoplayer-intro#9]
Hi, with Android Studio 3.0.1 I'm getting this error: "Error:Could not initialize class org.jetbrains.kotlin.kapt.idea.KaptModelBuilderService", so I can't even build the samples.

**Comment by marcbaechinger** [comment]
Not sure if this an issue with the code lab or the code here. This works for me with AS 3.0.1.

Closing now. Please reopen if you think this is an issue with the codelab still.
